# Método da Eliminação de Gauss com Pivotação Parcial
## Objetivo
O objetivo desse notebook é implementar o método da eliminação de Gauss com Pivotação Parcial.

## Implementação
Nós iremos implementar o algoritmo parte por parte, de acordo com a estratégia mostrada em sala. As instruções estão nos comentários nas funções abaixo. Você só precisa editar onde estiver indicado.

Iremos utilizar a biblioteca numpy para representar vetores e matrizes.

```python
import numpy as np

```

Para executar uma célula, selecione a célula e pressione ```Ctrl + Enter```. Após implementar as funções abaixo, você deve executar cada uma das células, preferencialmente na ordem em que elas aparecem.


In [3]:
import numpy as np

### Função para escolher o pivô

In [4]:
def escolhe_pivo(k, A, b):
    '''Escolhe o pivô de maior valor absoluto na coluna k a partir da linha k
       da matriz A. Se o pivô estiver numa linha diferente de k, as linhas da
       matriz A e do vetor b são trocadas (in place).
       Saída: booleano (True se houve troca)
    '''
    ## inicializa flag para controlar se houve troca de linha com false
    houve_troca = False
    ## encontra o índice da linha com o maior valor absoluto na coluna k,
    ## a partir da linha k
    ## dica: use np.abs para pegar o valor absoluto e np.argmax para pegar
    ## o índice do maior valor
    indice_pivo = k + np.argmax(np.abs(A[k:, k]))

    ## se k for diferente da linha onde está o pivô, troca a linha k
    ## pela linha do pivô em A e b e atribui o valor True à flag
    if indice_pivo != k:
        A[[k, indice_pivo]] = A[[indice_pivo, k]]
        b[[k, indice_pivo]] = b[[indice_pivo, k]]
        houve_troca = True
    ## retorna a flag
    return houve_troca

Agora precisamos testar se a função está implementada corretamente. Iremos testar com o exemplo mostrado em sala.

In [5]:
A = np.array([[1, 2, 3],
        [3, 1, 0],
        [0, 3, 4]])
b = np.array([3, 4, 3])
print("Antes da troca: A = \n", A)
print("Antes da troca: b = \n", b)

## Testaremos com a primeira coluna (k=0)
houveTroca = escolhe_pivo(0, A, b)
print("Houve troca? ", houveTroca)
print("Depois da troca A =\n", A)
print("Depois da troca b =\n", b)

Antes da troca: A = 
 [[1 2 3]
 [3 1 0]
 [0 3 4]]
Antes da troca: b = 
 [3 4 3]
Houve troca?  True
Depois da troca A =
 [[3 1 0]
 [1 2 3]
 [0 3 4]]
Depois da troca b =
 [4 3 3]


Se estiver tudo ok, ao executar a célula acima, você deve ver a resposta:
```
Antes da troca: A =
 [[1 2 3]
 [3 1 0]
 [0 3 4]]
Antes da troca: b =
 [3 4 3]
Houve troca?  True
Depois da troca A =
 [[3 1 0]
 [1 2 3]
 [0 3 4]]
Depois da troca b =
 [4 3 3]
```

### Método de Gauss com Pivotação

Copie a função ```substituicoes_retroativas``` que você implementou no notebook gauss.ipynb.


In [20]:
def substituicoes_retroativas(A, b):
    '''Executa o método das substituições retroativas para resolver o sistema
       linear triangular superior Ax=b.
       Parâmetros de entrada:
         - A: matriz triangular superior (numpy array 2D)
         - b: vetor constante (numpy array 1D)
       Saída: vetor x (numpy array 1D)
    '''
    n = A.shape[0]  # número de linhas (ou colunas, já que é quadrada)
    x = np.zeros(n)  # vetor solução inicializado com zeros

    # itera sobre as linhas de baixo para cima
    for i in range(n - 1, -1, -1):
        # calcula o valor de x[i] usando a equação da linha i
        s = np.dot(A[i, i + 1:], x[i + 1:])
        # resolve a equação para x[i]
        x[i] = (b[i] - s) / A[i, i]
    return x

Agora copie o conteúdo da função ```gauss``` que você implementou no notebook gauss.ipynb, modificando apenas a parte para escolher o pivô. O resto permanece igual.

In [28]:
def gauss_pivot(A, b):
    '''Executa o método da eliminação de Gauss com pivotação parcial para resolver
       o sistema linear Ax=b, transformando-o em um sistema triangular superior.
       Parâmetros de entrada:
         - A: matriz quadrada (numpy array 2D)
         - b: vetor constante (numpy array 1D)
       Saída: vetor x (numpy array 1D)
    '''
    ## Vamos copiar a matriz A e o vetor b para não alterar os dados originais
    A = A.copy().astype(float)  # Evita modificar A original
    b = b.copy().astype(float)  # Evita modificar b original

    # n é a ordem da matriz A
    n = A.shape[0]

    # Para cada etapa k
    for k in range(0, n-1):
        escolhe_pivo(k, A, b)
        # Para cada linha i
        for i in range(k+1, n):
            # Calcula o fator de multiplicação
            m = -A[i, k] / A[k, k]
            # Atualiza a linha i da matriz A, a partir da linha k+1
            A[i, k+1:] = m * A[k, k+1:] + A[i, k+1:]
            # Atualiza o vetor b
            b[i] = m * b[k] + b[i]
            # Zera o elemento A[i, k]
            A[i, k] = 0.0
    # Agora resolve o sistema triangular superior usando substituições retroativas
    x = substituicoes_retroativas(A, b)
    return x

**Não se esqueça de executar as células de código acima!**

Agora precisamos testar se a função está implementada corretamente. Também iremos usar o exemplo mostrado em sala.

In [29]:
A = np.array([[1, 2, 3],
    [3, 1, 0],
    [0, 3, 4]])
b = np.array([3, 4, 3])
x = gauss_pivot(A, b)
print(x)

[1. 1. 0.]


Se estiver tudo ok, ao executar a célula acima, você deve ver a resposta:
```
[1., 1., 0.]
```
### Exercício 1
Na célula abaixo, teste o método resolvendo o exercício mostrado em sala:

$\left[\begin{array}{rrr}
1& -3 & 2\\
-2& 8 & -1\\
4& -6 & 5\\
\end{array}\right] \left[\begin{array}{c}
x_1\\
x_2\\
x_3\\
\end{array}\right] = \left[\begin{array}{r}
11\\
-15\\
29\\
\end{array}\right] $

In [30]:
# Defina a matriz A e o vetor b e chame a função gauss_pivot
A = np.array([[1, -3, 2],
            [-2, 8, -1],
            [4, -6, 5]])

b = np.array([11, -15, 29])
x = gauss_pivot(A, b)
print("Solução do sistema Ax=b:")
print(x)

Solução do sistema Ax=b:
[ 2. -1.  3.]


### Exercício 2
Na célula abaixo, o seguinte sistema linear:

$\left[\begin{array}{rrr}
3& 2 & 4\\
1& 1 & 2\\
4& 3 & -2\\
\end{array}\right] \left[\begin{array}{c}
x_1\\
x_2\\
x_3\\
\end{array}\right] = \left[\begin{array}{r}
1\\
2\\
3\\
\end{array}\right] $

In [31]:
A = np.array([[3, 2, 4],
              [1, 1, 2],
              [4, 3, -2]])
b = np.array([1, 2, 3])
x = gauss_pivot(A, b)
print("Solução do sistema Ax=b:")
print(x)

Solução do sistema Ax=b:
[-3.  5.  0.]


### Exercício 3

Modifique o método de gauss com pivotação para também calcular o determinante.
Use o valor retornado pela função ```escolhe_pivo``` para controlar o número de permutações, P.

$det(A) = (-1)^P \times det(U)$

In [37]:
def gauss_pivot_det(A, b):
    '''Executa o método da eliminação de Gauss com pivotação parcial para resolver
       o sistema linear Ax=b, transformando-o em um sistema triangular superior.
       Parâmetros de entrada:
         - A: matriz quadrada (numpy array 2D)
         - b: vetor constante (numpy array 1D)
       Saída: tupla (x, det), onde x é o vetor solução e det é o determinante da matriz A
    '''
    ## Vamos copiar a matriz A e o vetor b para não alterar os dados originais
    A = A.copy().astype(float)
    b = b.copy().astype(float)

    ## n é a ordem da matriz A
    n = A.shape[0]
    # P é o número de trocas de linha
    P = 0

    ## Para cada etapa k
        ## Escolhe o pivô
    for k in range(0, n-1):
      if escolhe_pivo(k, A, b):
        P += 1

      for i in range(k+1, n):
            # Calcula o fator de multiplicação
            m = -A[i, k] / A[k, k]
            # Atualiza a linha i da matriz A, a partir da linha k+1
            A[i, k+1:] = m * A[k, k+1:] + A[i, k+1:]
            # Atualiza o vetor b
            b[i] = m * b[k] + b[i]
            # Zera o elemento A[i, k]
            A[i, k] = 0.0

    ## Calcula o determinante da matriz A
    det = np.prod(np.diag(A))
    det = det * (-1)**P  # Ajusta o sinal do determinante se houve troca de linhas
   
    if det != 0:
        x = substituicoes_retroativas(A, b)
    else:
        x = None
        print("O sistema não tem solução única (determinante é zero).")
  
    return x, det

Agora teste com o exemplo acima:

$\left[\begin{array}{rrr}
1& -3 & 2\\
-2& 8 & -1\\
4& -6 & 5\\
\end{array}\right] \left[\begin{array}{c}
x_1\\
x_2\\
x_3\\
\end{array}\right] = \left[\begin{array}{r}
11\\
-15\\
29\\
\end{array}\right] $

In [38]:
A = np.array([[1, -3, 2],
              [-2, 8, -1],
              [4, -6, 5]])
b = np.array([11, -15, 29])
x, det = gauss_pivot_det(A, b)
print("Solução do sistema Ax=b:")
print(x)
print("Determinante da matriz A:")
print(det)

Solução do sistema Ax=b:
[ 2. -1.  3.]
Determinante da matriz A:
-24.0


Se tudo deu certo, você deve obter a seguinte resposta:

```
[2., -1., 3.]  -24.0
```


Agora teste com o seguinte sistema de matriz dos coeficientes singular:

$\left[\begin{array}{rrr}
1& -3 & 2\\
1& -3 & 2\\
4& -6 & 5\\
\end{array}\right] \left[\begin{array}{c}
x_1\\
x_2\\
x_3\\
\end{array}\right] = \left[\begin{array}{r}
11\\
-15\\
29\\
\end{array}\right] $

In [39]:
A = np.array([[1, -3, 2],
              [1, -3, 2],
              [4, -6, 5]])
b = np.array([11, -15, 29])
x, det = gauss_pivot_det(A, b)
print("Solução do sistema Ax=b:")
print(x)
print("Determinante da matriz A:")
print(det)

O sistema não tem solução única (determinante é zero).
Solução do sistema Ax=b:
None
Determinante da matriz A:
0.0
